/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.resume.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.portlet.asset.service.persistence.AssetEntryPersistence;
import com.liferay.portlet.ratings.service.persistence.RatingsStatsPersistence;

import com.resume.model.Resume;

import com.resume.service.ResumeLocalService;
import com.resume.service.persistence.DetailsPersistence;
import com.resume.service.persistence.ResumePersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the resume local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.resume.service.impl.ResumeLocalServiceImpl}.
 * </p>
 *
 * @author Artyom
 * @see com.resume.service.impl.ResumeLocalServiceImpl
 * @see com.resume.service.ResumeLocalServiceUtil
 * @generated
 */
public abstract class ResumeLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements ResumeLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.resume.service.ResumeLocalServiceUtil} to access the resume local service.
	 */

	/**
	 * Adds the resume to the database. Also notifies the appropriate model listeners.
	 *
	 * @param resume the resume
	 * @return the resume that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Resume addResume(Resume resume) throws SystemException {
		resume.setNew(true);

		return resumePersistence.update(resume);
	}

	/**
	 * Creates a new resume with the primary key. Does not add the resume to the database.
	 *
	 * @param resumeId the primary key for the new resume
	 * @return the new resume
	 */
	@Override
	public Resume createResume(long resumeId) {
		return resumePersistence.create(resumeId);
	}

	/**
	 * Deletes the resume with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param resumeId the primary key of the resume
	 * @return the resume that was removed
	 * @throws PortalException if a resume with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Resume deleteResume(long resumeId)
		throws PortalException, SystemException {
		return resumePersistence.remove(resumeId);
	}

	/**
	 * Deletes the resume from the database. Also notifies the appropriate model listeners.
	 *
	 * @param resume the resume
	 * @return the resume that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Resume deleteResume(Resume resume) throws SystemException {
		return resumePersistence.remove(resume);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(Resume.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return resumePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.resume.model.impl.ResumeModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return resumePersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.resume.model.impl.ResumeModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return resumePersistence.findWithDynamicQuery(dynamicQuery, start, end,
			orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return resumePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return resumePersistence.countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public Resume fetchResume(long resumeId) throws SystemException {
		return resumePersistence.fetchByPrimaryKey(resumeId);
	}

	/**
	 * Returns the resume with the matching UUID and company.
	 *
	 * @param uuid the resume's UUID
	 * @param  companyId the primary key of the company
	 * @return the matching resume, or <code>null</code> if a matching resume could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public Resume fetchResumeByUuidAndCompanyId(String uuid, long companyId)
		throws SystemException {
		return resumePersistence.fetchByUuid_C_First(uuid, companyId, null);
	}

	/**
	 * Returns the resume matching the UUID and group.
	 *
	 * @param uuid the resume's UUID
	 * @param groupId the primary key of the group
	 * @return the matching resume, or <code>null</code> if a matching resume could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public Resume fetchResumeByUuidAndGroupId(String uuid, long groupId)
		throws SystemException {
		return resumePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the resume with the primary key.
	 *
	 * @param resumeId the primary key of the resume
	 * @return the resume
	 * @throws PortalException if a resume with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public Resume getResume(long resumeId)
		throws PortalException, SystemException {
		return resumePersistence.findByPrimaryKey(resumeId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return resumePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the resume with the matching UUID and company.
	 *
	 * @param uuid the resume's UUID
	 * @param  companyId the primary key of the company
	 * @return the matching resume
	 * @throws PortalException if a matching resume could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public Resume getResumeByUuidAndCompanyId(String uuid, long companyId)
		throws PortalException, SystemException {
		return resumePersistence.findByUuid_C_First(uuid, companyId, null);
	}

	/**
	 * Returns the resume matching the UUID and group.
	 *
	 * @param uuid the resume's UUID
	 * @param groupId the primary key of the group
	 * @return the matching resume
	 * @throws PortalException if a matching resume could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public Resume getResumeByUuidAndGroupId(String uuid, long groupId)
		throws PortalException, SystemException {
		return resumePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the resumes.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.resume.model.impl.ResumeModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of resumes
	 * @param end the upper bound of the range of resumes (not inclusive)
	 * @return the range of resumes
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<Resume> getResumes(int start, int end)
		throws SystemException {
		return resumePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of resumes.
	 *
	 * @return the number of resumes
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getResumesCount() throws SystemException {
		return resumePersistence.countAll();
	}

	/**
	 * Updates the resume in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param resume the resume
	 * @return the resume that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Resume updateResume(Resume resume) throws SystemException {
		return resumePersistence.update(resume);
	}

	/**
	 * Returns the details local service.
	 *
	 * @return the details local service
	 */
	public com.resume.service.DetailsLocalService getDetailsLocalService() {
		return detailsLocalService;
	}

	/**
	 * Sets the details local service.
	 *
	 * @param detailsLocalService the details local service
	 */
	public void setDetailsLocalService(
		com.resume.service.DetailsLocalService detailsLocalService) {
		this.detailsLocalService = detailsLocalService;
	}

	/**
	 * Returns the details persistence.
	 *
	 * @return the details persistence
	 */
	public DetailsPersistence getDetailsPersistence() {
		return detailsPersistence;
	}

	/**
	 * Sets the details persistence.
	 *
	 * @param detailsPersistence the details persistence
	 */
	public void setDetailsPersistence(DetailsPersistence detailsPersistence) {
		this.detailsPersistence = detailsPersistence;
	}

	/**
	 * Returns the resume local service.
	 *
	 * @return the resume local service
	 */
	public com.resume.service.ResumeLocalService getResumeLocalService() {
		return resumeLocalService;
	}

	/**
	 * Sets the resume local service.
	 *
	 * @param resumeLocalService the resume local service
	 */
	public void setResumeLocalService(
		com.resume.service.ResumeLocalService resumeLocalService) {
		this.resumeLocalService = resumeLocalService;
	}

	/**
	 * Returns the resume persistence.
	 *
	 * @return the resume persistence
	 */
	public ResumePersistence getResumePersistence() {
		return resumePersistence;
	}

	/**
	 * Sets the resume persistence.
	 *
	 * @param resumePersistence the resume persistence
	 */
	public void setResumePersistence(ResumePersistence resumePersistence) {
		this.resumePersistence = resumePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Returns the asset entry local service.
	 *
	 * @return the asset entry local service
	 */
	public com.liferay.portlet.asset.service.AssetEntryLocalService getAssetEntryLocalService() {
		return assetEntryLocalService;
	}

	/**
	 * Sets the asset entry local service.
	 *
	 * @param assetEntryLocalService the asset entry local service
	 */
	public void setAssetEntryLocalService(
		com.liferay.portlet.asset.service.AssetEntryLocalService assetEntryLocalService) {
		this.assetEntryLocalService = assetEntryLocalService;
	}

	/**
	 * Returns the asset entry remote service.
	 *
	 * @return the asset entry remote service
	 */
	public com.liferay.portlet.asset.service.AssetEntryService getAssetEntryService() {
		return assetEntryService;
	}

	/**
	 * Sets the asset entry remote service.
	 *
	 * @param assetEntryService the asset entry remote service
	 */
	public void setAssetEntryService(
		com.liferay.portlet.asset.service.AssetEntryService assetEntryService) {
		this.assetEntryService = assetEntryService;
	}

	/**
	 * Returns the asset entry persistence.
	 *
	 * @return the asset entry persistence
	 */
	public AssetEntryPersistence getAssetEntryPersistence() {
		return assetEntryPersistence;
	}

	/**
	 * Sets the asset entry persistence.
	 *
	 * @param assetEntryPersistence the asset entry persistence
	 */
	public void setAssetEntryPersistence(
		AssetEntryPersistence assetEntryPersistence) {
		this.assetEntryPersistence = assetEntryPersistence;
	}

	/**
	 * Returns the ratings stats local service.
	 *
	 * @return the ratings stats local service
	 */
	public com.liferay.portlet.ratings.service.RatingsStatsLocalService getRatingsStatsLocalService() {
		return ratingsStatsLocalService;
	}

	/**
	 * Sets the ratings stats local service.
	 *
	 * @param ratingsStatsLocalService the ratings stats local service
	 */
	public void setRatingsStatsLocalService(
		com.liferay.portlet.ratings.service.RatingsStatsLocalService ratingsStatsLocalService) {
		this.ratingsStatsLocalService = ratingsStatsLocalService;
	}

	/**
	 * Returns the ratings stats persistence.
	 *
	 * @return the ratings stats persistence
	 */
	public RatingsStatsPersistence getRatingsStatsPersistence() {
		return ratingsStatsPersistence;
	}

	/**
	 * Sets the ratings stats persistence.
	 *
	 * @param ratingsStatsPersistence the ratings stats persistence
	 */
	public void setRatingsStatsPersistence(
		RatingsStatsPersistence ratingsStatsPersistence) {
		this.ratingsStatsPersistence = ratingsStatsPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.resume.model.Resume",
			resumeLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.resume.model.Resume");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return Resume.class;
	}

	protected String getModelClassName() {
		return Resume.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = resumePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.resume.service.DetailsLocalService.class)
	protected com.resume.service.DetailsLocalService detailsLocalService;
	@BeanReference(type = DetailsPersistence.class)
	protected DetailsPersistence detailsPersistence;
	@BeanReference(type = com.resume.service.ResumeLocalService.class)
	protected com.resume.service.ResumeLocalService resumeLocalService;
	@BeanReference(type = ResumePersistence.class)
	protected ResumePersistence resumePersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@BeanReference(type = com.liferay.portlet.asset.service.AssetEntryLocalService.class)
	protected com.liferay.portlet.asset.service.AssetEntryLocalService assetEntryLocalService;
	@BeanReference(type = com.liferay.portlet.asset.service.AssetEntryService.class)
	protected com.liferay.portlet.asset.service.AssetEntryService assetEntryService;
	@BeanReference(type = AssetEntryPersistence.class)
	protected AssetEntryPersistence assetEntryPersistence;
	@BeanReference(type = com.liferay.portlet.ratings.service.RatingsStatsLocalService.class)
	protected com.liferay.portlet.ratings.service.RatingsStatsLocalService ratingsStatsLocalService;
	@BeanReference(type = RatingsStatsPersistence.class)
	protected RatingsStatsPersistence ratingsStatsPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private ResumeLocalServiceClpInvoker _clpInvoker = new ResumeLocalServiceClpInvoker();
}