/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.resume.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.resume.model.Resume;

import com.resume.service.ResumeLocalServiceUtil;

/**
 * The extended model base implementation for the Resume service. Represents a row in the &quot;resume_Resume&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ResumeImpl}.
 * </p>
 *
 * @author Artyom
 * @see ResumeImpl
 * @see com.resume.model.Resume
 * @generated
 */
public abstract class ResumeBaseImpl extends ResumeModelImpl implements Resume {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a resume model instance should use the {@link Resume} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			ResumeLocalServiceUtil.addResume(this);
		}
		else {
			ResumeLocalServiceUtil.updateResume(this);
		}
	}
}