/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.resume.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Details service. Represents a row in the &quot;resume_Details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.resume.model.impl.DetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.resume.model.impl.DetailsImpl}.
 * </p>
 *
 * @author Artyom
 * @see Details
 * @see com.resume.model.impl.DetailsImpl
 * @see com.resume.model.impl.DetailsModelImpl
 * @generated
 */
public interface DetailsModel extends BaseModel<Details> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a details model instance should use the {@link Details} interface instead.
	 */

	/**
	 * Returns the primary key of this details.
	 *
	 * @return the primary key of this details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this details.
	 *
	 * @param primaryKey the primary key of this details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the details ID of this details.
	 *
	 * @return the details ID of this details
	 */
	public long getDetailsId();

	/**
	 * Sets the details ID of this details.
	 *
	 * @param detailsId the details ID of this details
	 */
	public void setDetailsId(long detailsId);

	/**
	 * Returns the surname of this details.
	 *
	 * @return the surname of this details
	 */
	@AutoEscape
	public String getSurname();

	/**
	 * Sets the surname of this details.
	 *
	 * @param surname the surname of this details
	 */
	public void setSurname(String surname);

	/**
	 * Returns the name of this details.
	 *
	 * @return the name of this details
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this details.
	 *
	 * @param name the name of this details
	 */
	public void setName(String name);

	/**
	 * Returns the patronymic of this details.
	 *
	 * @return the patronymic of this details
	 */
	@AutoEscape
	public String getPatronymic();

	/**
	 * Sets the patronymic of this details.
	 *
	 * @param patronymic the patronymic of this details
	 */
	public void setPatronymic(String patronymic);

	/**
	 * Returns the address of this details.
	 *
	 * @return the address of this details
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this details.
	 *
	 * @param address the address of this details
	 */
	public void setAddress(String address);

	/**
	 * Returns the phonenumber of this details.
	 *
	 * @return the phonenumber of this details
	 */
	@AutoEscape
	public String getPhonenumber();

	/**
	 * Sets the phonenumber of this details.
	 *
	 * @param phonenumber the phonenumber of this details
	 */
	public void setPhonenumber(String phonenumber);

	/**
	 * Returns the email of this details.
	 *
	 * @return the email of this details
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this details.
	 *
	 * @param email the email of this details
	 */
	public void setEmail(String email);

	/**
	 * Returns the position of this details.
	 *
	 * @return the position of this details
	 */
	@AutoEscape
	public String getPosition();

	/**
	 * Sets the position of this details.
	 *
	 * @param position the position of this details
	 */
	public void setPosition(String position);

	/**
	 * Returns the education of this details.
	 *
	 * @return the education of this details
	 */
	@AutoEscape
	public String getEducation();

	/**
	 * Sets the education of this details.
	 *
	 * @param education the education of this details
	 */
	public void setEducation(String education);

	/**
	 * Returns the knowledge of this details.
	 *
	 * @return the knowledge of this details
	 */
	@AutoEscape
	public String getKnowledge();

	/**
	 * Sets the knowledge of this details.
	 *
	 * @param knowledge the knowledge of this details
	 */
	public void setKnowledge(String knowledge);

	/**
	 * Returns the experience of this details.
	 *
	 * @return the experience of this details
	 */
	@AutoEscape
	public String getExperience();

	/**
	 * Sets the experience of this details.
	 *
	 * @param experience the experience of this details
	 */
	public void setExperience(String experience);

	/**
	 * Returns the quailities of this details.
	 *
	 * @return the quailities of this details
	 */
	@AutoEscape
	public String getQuailities();

	/**
	 * Sets the quailities of this details.
	 *
	 * @param quailities the quailities of this details
	 */
	public void setQuailities(String quailities);

	/**
	 * Returns the additionally of this details.
	 *
	 * @return the additionally of this details
	 */
	@AutoEscape
	public String getAdditionally();

	/**
	 * Sets the additionally of this details.
	 *
	 * @param additionally the additionally of this details
	 */
	public void setAdditionally(String additionally);

	/**
	 * Returns the resume ID of this details.
	 *
	 * @return the resume ID of this details
	 */
	public long getResumeId();

	/**
	 * Sets the resume ID of this details.
	 *
	 * @param resumeId the resume ID of this details
	 */
	public void setResumeId(long resumeId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Details details);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Details> toCacheModel();

	@Override
	public Details toEscapedModel();

	@Override
	public Details toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}